# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'ubuntu-agent'
  vmImage: ubuntu-latest

variables:
  environment: <name_of_environment>
  collection: <name_of_collection>
  
steps:
  - name: Run Postman Collection
    script:
      pm run $collection --environment $environment
